title: Aaron Rietschlin — Resume
url: "https://aaron.rietschlin.com"
baseurl: ""

remote_theme: sharu725/online-cv
theme_skin: ceramic

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
